name: autofix.ci
on:
  push:
    branches:
      - trunk
    paths:
      - "**.html"
      - "**.css"
      - "**.js"
      - "**.md"
      - "**.tsx"
      - "**.json"
  pull_request:
    branches:
      - trunk
  merge_group:
    types: [checks_requested]
  page_build:
permissions: {}
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: |
          yarn
          yarn prettier . --check
      - uses: autofix-ci/action@v1
        with:
          commit-message: "prettier"
